theme: minima
title: My site
description: This site is a collection of my personal projects together with academic- & work experience

contact-list: "Test"

header_pages:
  - headerpages/rfbyboesen.md
  - headerpages/about.md