theme: minima
title: My site
description: A collection of my personal projects and my academic- & work experience
author: Victor Boesen

twitter_username: victor_boesen
github_username:  byggemandboesen
linkedin_username: victor-boesen-gandloese

header_pages:
  - headerpages/projects/projects.md
  - headerpages/cv/cv.md
  - headerpages/precisionworks/precisionworks.md
  - headerpages/about/about.md
  - headerpages/contact/contact.md

exclude:
  - README.md